# Generated by Django 6.0.1 on 2026-01-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_user_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='task_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='primeitem',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
