# Generated by Django 6.0.1 on 2026-02-01 09:15

from django.db import migrations, models
from django.utils import timezone
import math


def backfill_primeitem_last_primed_at(apps, schema_editor):
    PrimeItem = apps.get_model("tracker", "PrimeItem")
    batch_size = 500
    pending = []

    queryset = PrimeItem.objects.all().only("id", "prime_timestamps")
    for item in queryset.iterator(chunk_size=batch_size):
        timestamps = item.prime_timestamps or []
        numeric = []
        for ts in timestamps:
            if isinstance(ts, (int, float)) and math.isfinite(ts):
                numeric.append(ts)
            elif isinstance(ts, str) and ts.isdigit():
                numeric.append(int(ts))
        if not numeric:
            continue
        last_ts = max(numeric)
        item.last_primed_at = timezone.datetime.fromtimestamp(
            last_ts / 1000, tz=timezone.UTC
        )
        pending.append(item)

        if len(pending) >= batch_size:
            PrimeItem.objects.bulk_update(pending, ["last_primed_at"])
            pending = []

    if pending:
        PrimeItem.objects.bulk_update(pending, ["last_primed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_moment_task_title_alter_primeitem_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="primeitem",
            name="last_primed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_primeitem_last_primed_at, migrations.RunPython.noop),
    ]
