# Generated by Django 6.0.1 on 2026-02-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0004_primeitem_last_primed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("study_timestamps", models.JSONField(blank=True, default=list)),
                (
                    "first_studied_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_studied_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "source_prime_item_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reviewitem",
            name="source_study_item_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
