# Generated by Django 6.0.1 on 2026-02-11 20:55

import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_studyitem_reviewitem_source_study_item_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primeitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewitem',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='studyitem',
            options={'ordering': ['-last_studied_at', 'created_at']},
        ),
        migrations.RenameField(
            model_name='studyitem',
            old_name='study_timestamps',
            new_name='interaction_timestamps',
        ),
        migrations.RenameField(
            model_name='studyitem',
            old_name='archived',
            new_name='is_archived',
        ),
        migrations.RemoveField(
            model_name='studyitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studyitem',
            name='source_prime_item_id',
        ),
        migrations.RemoveField(
            model_name='studyitem',
            name='title',
        ),
        migrations.AddField(
            model_name='studyitem',
            name='first_primed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='first_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tracker.models.study_item_image_path),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='is_priming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='is_reviewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='last_primed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='prime_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='prompt',
            field=models.TextField(default='None', max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyitem',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='study_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studyitem',
            name='category',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name='studyitem',
            index=models.Index(fields=['user', 'is_priming', 'is_archived'], name='tracker_stu_user_id_2f093d_idx'),
        ),
        migrations.AddIndex(
            model_name='studyitem',
            index=models.Index(fields=['user', 'is_studying', 'is_archived'], name='tracker_stu_user_id_8e5e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='studyitem',
            index=models.Index(fields=['user', 'is_reviewing', 'is_archived'], name='tracker_stu_user_id_26588a_idx'),
        ),
        migrations.AddIndex(
            model_name='studyitem',
            index=models.Index(fields=['user', 'is_archived'], name='tracker_stu_user_id_071795_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_priming', True), ('is_reviewing', False), ('is_studying', False)), models.Q(('is_priming', False), ('is_reviewing', False), ('is_studying', True)), models.Q(('is_priming', False), ('is_reviewing', True), ('is_studying', False)), _connector='OR'), name='exactly_one_mode_active'),
        ),
        migrations.DeleteModel(
            name='PrimeItem',
        ),
        migrations.DeleteModel(
            name='ReviewItem',
        ),
    ]
