# Generated by Django 6.0.1 on 2026-02-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_primeitem_user_remove_reviewitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studyitem',
            name='prompt',
            field=models.TextField(blank=True, default='', max_length=20000),
        ),
    ]
