# Generated by Django 6.0.1 on 2026-02-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_studyitem_notes_alter_studyitem_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyitem',
            name='prompt',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
    ]
