# Generated by Django 6.0.1 on 2026-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_studyitem_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyitem',
            old_name='interaction_timestamps',
            new_name='prime_timestamps',
        ),
        migrations.AddField(
            model_name='studyitem',
            name='review_timestamps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='study_timestamps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
