# Generated by Django 6.0.1 on 2026-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_interaction_timestamps_studyitem_prime_timestamps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_logged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
