# Generated by Django 6.0.1 on 2026-03-02 08:44

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_habit_last_completed_date_habit_last_logged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to=tracker.models.study_item_note_image_path),
        ),
    ]
