# Generated by Django 6.0.1 on 2026-03-20 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    UserModel = apps.get_model("auth", "User")
    UserSubscription = apps.get_model("tracker", "UserSubscription")
    for user in UserModel.objects.all():
        UserSubscription.objects.get_or_create(
            user=user,
            defaults={
                "is_grandfathered": True,
                "trial_ends_at": None,
                "is_subscribed": False,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grandfathered', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(grandfather_existing_users, noop_reverse),
    ]
