# Generated by Django 6.0.1 on 2026-09-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
